---
abstract: 'Net::DNS interface to several DNS backends via API'
author:
  - 'Lenz Gschwendtner, C<< <norbu09 at cpan.org> >>'
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS-Abstract
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Any::Moose: 0
  Module::Load: 0
  Net::DNS: 0
  True::Truth: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
